# Tratamento de dados

In [1]:
import os
import re
import numpy as np
import pandas as pd
from bs4 import BeautifulSoup
from datetime import datetime

### Statements

In [71]:
df_statements = pd.read_csv('statements.csv')

In [72]:
# df_statements['Type'] = 'Statement'
df_statements["Date"] = df_statements["Data"].apply(pd.to_datetime, format='%Y-%m-%d %H:%M:%S.%f').dt.strftime('%Y/%m/%d')
df_statements.drop(['Data', 'Id', 'Titulo', 'DataAtualizacao', 'mostrarCabecalho', 'mostrarRodape'], axis=1, inplace=True)

In [73]:
df_statements.rename(columns={'Conteudo': 'Statements'}, inplace=True)
df_statements.sort_values('Date', inplace=True)
df_statements.set_index('Date', inplace=True)

In [74]:
df_statements['Statements'] = df_statements['Statements'].apply(lambda x: BeautifulSoup(x, features="html.parser").get_text())

In [75]:
df_statements.head(5)

                                                   Statements
Date
2006/03/08   In the March Meeting, the Banco Central do Br...
2006/04/19   In the April Meeting, the Monetary Policy Com...
2006/05/31   In the May Meeting, the Monetary Policy Commi...
2006/07/19   In the July Meeting, the Copom unanimously de...
2006/08/30   In the August Meeting, the Copom unanimously ...

### Minutes

In [76]:
df_minutes = pd.read_csv('minutes.csv')

In [77]:
# df_minutes['Type'] = 'Minutes'
df_minutes["Minutes_Date"] = df_minutes["data"].apply(pd.to_datetime).dt.strftime('%Y/%m/%d')
df_minutes["Date"] = df_minutes["DataReferencia"].apply(pd.to_datetime).dt.strftime('%Y/%m/%d')

In [78]:
df_minutes.drop(['data', 'DataReferencia', 'BoxDestaque', 'Edicao', 'EsconderCapa', 
                 'EsconderDataReferencia', 'Grafico', 'Id', 
                 'ImagemCapa', 'ImagemCapa', 'LinkPagina', 'Url',
                 'Volume', 'Volume', 'Introducao', 'conteudo', 'Titulo'], axis=1, inplace=True)

In [79]:
df_minutes.rename(columns={'data': 'Date', 'DataReferencia': 'Meeting_Date', 'OutrasInformacoes': 'Minutes'}, inplace=True)
df_minutes.sort_values('Date', inplace=True)
df_minutes.set_index('Date', inplace=True)

In [80]:
df_minutes = df_minutes[df_minutes['Minutes'].notna()]

In [81]:
df_minutes['Minutes'] = df_minutes['Minutes'].apply(lambda x: BeautifulSoup(x, features="html.parser").get_text())

In [82]:
df_minutes.head(5)

                                                      Minutes Minutes_Date
Date
2020/08/05  1. Regarding the global outlook, the Covid-19 ...   2020/08/11
2020/09/16  A) Update of economic outlook and Copom’s base...   2020/09/22
2020/10/28  A) Update of economic outlook and Copom’s base...   2020/12/15
2020/12/09  A) Update of economic outlook and Copom’s base...   2020/12/15
2021/01/20  A) Update of economic outlook and Copom’s base...   2021/01/26

### Decisions

In [46]:
df_decisions = pd.read_csv('decisions.csv')

In [47]:
df_decisions.drop(['DataFimVigencia', 'DataInicioVigencia', 'TaxaSelicEfetivaAnualizada',
                 'TaxaSelicEfetivaVigencia', 'TaxaTban', 'UsoMetaSelic', 'ReuniaoExtraordinaria',
                 'Vies'], axis=1, inplace=True)

In [48]:
df_decisions["DataReuniaoCopom"] = df_decisions["DataReuniaoCopom"].apply(pd.to_datetime).dt.strftime('%Y/%m/%d')

In [49]:
df_decisions.rename(columns={'DataReuniaoCopom': 'Date', 
                             'MetaSelic': 'Selic', 
                             'NumeroReuniaoCopom': 'Meeting_Number'
                            }, inplace=True)

In [50]:
df_decisions = df_decisions[df_decisions['Date'] != 'NaT']

In [51]:
df_decisions.sort_values('Date', inplace=True)
df_decisions.set_index('Date', inplace=True)

In [52]:
i = 0
df_decisions['Decision'] = np.nan
df_decisions['Decision_txt'] = ''

In [53]:
for i in range(len(df_decisions)-1):
    df_decisions['Decision'].iloc[i+1] = df_decisions['Selic'].iloc[i+1]-df_decisions['Selic'].iloc[i]

C:\Users\ftrav\anaconda3\envs\pytorchenv\lib\site-packages\pandas\core\indexing.py:190: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._setitem_with_indexer(indexer, value)

In [54]:
def decision_txt(num):
    if num == 0:
        return 'mantain'
    elif num >= 0:
        return 'increase'
    elif num <= 0:
        return 'decrease'
    else:
        return ''

In [55]:
for i in range(len(df_decisions)-1):
    df_decisions['Decision_txt'].iloc[i+1] = decision_txt(df_decisions['Decision'].iloc[i+1])

In [56]:
df_decisions.tail(5)

            Selic  Meeting_Number  Decision Decision_txt
Date
2022/10/26  13.75           250.0       0.0      mantain
2022/12/07  13.75           251.0       0.0      mantain
2023/02/01  13.75           252.0       0.0      mantain
2023/03/22  13.75           253.0       0.0      mantain
2023/05/03  13.75           254.0       0.0      mantain

### Merge columns

In [85]:
df1 = pd.merge(df_statements, df_minutes, how="outer", on="Date")

In [87]:
df = pd.merge(df1, df_decisions, how="outer", on="Date")

In [89]:
df.sort_values('Date', inplace=True)

In [90]:
df

,Statements,Minutes,Minutes_Date,Selic,Meeting_Number,Decision,Decision_txt
Date,,,,,,,
1996/06/26,NaN,NaN,NaN,1.90,1.0,NaN,
1996/07/30,NaN,NaN,NaN,1.90,2.0,0.00,mantain
1996/08/21,NaN,NaN,NaN,1.88,3.0,-0.02,decrease
1996/09/23,NaN,NaN,NaN,1.82,4.0,-0.06,decrease
1996/10/23,NaN,NaN,NaN,1.78,5.0,-0.04,decrease
1996/11/27,NaN,NaN,NaN,1.74,6.0,-0.04,decrease
1996/12/18,NaN,NaN,NaN,1.70,7.0,-0.04,decrease
1997/01/22,NaN,NaN,NaN,1.66,8.0,-0.04,decrease
1997/02/19,NaN,NaN,NaN,1.62,9.0,-0.04,decrease
1997/03/19,NaN,NaN,NaN,1.58,10.0,-0.04,decrease
1997/04/16,NaN,NaN,NaN,1.58,11.0,0.00,mantain
1997/05/21,NaN,NaN,NaN,1.58,12.0,0.00,mantain
1997/06/18,NaN,NaN,NaN,1.58,13.0,0.00,mantain
1997/07/23,NaN,NaN,NaN,1.58,14.0,0.00,mantain
1997/08/20,NaN,NaN,NaN,1.58,15.0,0.00,mantain
1997/09/17,NaN,NaN,NaN,1.58,16.0,0.00,mantain
1997/10/22,NaN,NaN,NaN,1.00,17.0,-0.58,decrease
1997/10/30,NaN,NaN,NaN,3.05,18.0,2.05,increase
1997/11/19,NaN,NaN,NaN,2.90,19.0,-0.15,decrease
1997/12/17,NaN,NaN,NaN,38.00,20.0,35.10,increase
1998/01/28,NaN,NaN,NaN,34.50,21.0,-3.50,decrease
1998/03/04,NaN,NaN,NaN,28.00,22.0,-6.50,decrease
1998/04/15,NaN,NaN,NaN,23.25,23.0,-4.75,decrease
1998/05/20,NaN,NaN,NaN,21.75,24.0,-1.50,decrease
1998/06/24,NaN,NaN,NaN,21.00,25.0,-0.75,decrease
1998/07/29,NaN,NaN,NaN,19.75,26.0,-1.25,decrease
1998/09/02,NaN,NaN,NaN,19.00,27.0,-0.75,decrease
1998/09/10,NaN,NaN,NaN,19.00,28.0,0.00,mantain
1998/10/07,NaN,NaN,NaN,19.00,29.0,0.00,mantain
1998/11/11,NaN,NaN,NaN,19.00,30.0,0.00,mantain
...,...,...,...,...,...,...,...
2019/09/18,"In its 225th meeting, the Copom unanimously de...",NaN,NaN,5.50,225.0,-0.50,decrease
2019/10/30,"​In its 226th meeting, the Copom unanimously d...",NaN,NaN,5.00,226.0,-0.50,decrease
2019/12/11,"In its 227th meeting, the Copom unanimously de...",NaN,NaN,4.50,227.0,-0.50,decrease
2020/02/05,"In its 228th meeting, the Copom unanimously de...",NaN,NaN,4.25,228.0,-0.25,decrease
2020/03/18,"In its 229th meeting, the Copom unanimously de...",NaN,NaN,3.75,229.0,-0.50,decrease
2020/05/06,"In its 230th meeting, the Copom unanimously de...",NaN,NaN,3.00,230.0,-0.75,decrease
2020/06/17,"In its 231st meeting, the Copom unanimously de...",NaN,NaN,2.25,231.0,-0.75,decrease
2020/08/05,"In its 232nd meeting, the Copom unanimously de...","1. Regarding the global outlook, the Covid-19 ...",2020/08/11,2.00,232.0,-0.25,decrease
2020/09/16,"​In its 233rd meeting, the Copom unanimously d...",A) Update of economic outlook and Copom’s base...,2020/09/22,2.00,233.0,0.00,mantain
2020/10/28,"​In its 234th meeting, the Copom unanimously d...",A) Update of economic outlook and Copom’s base...,2020/12/15,2.00,234.0,0.00,mantain
2020/12/09,"In its 235th meeting, the Copom unanimously de...",A) Update of economic outlook and Copom’s base...,2020/12/15,2.00,235.0,0.00,mantain
2021/01/20,"In its 236th meeting, the Copom unanimously de...",A) Update of economic outlook and Copom’s base...,2021/01/26,2.00,236.0,0.00,mantain
2021/03/17,"​In its 237th meeting, the Copom unanimously d...",A) Update of economic outlook and Copom’s base...,2021/03/23,2.75,237.0,0.75,increase
2021/05/05,"In its 238th meeting, the Copom unanimously de...",A) Update of economic outlook and Copom’s base...,2021/05/11,3.50,238.0,0.75,increase
2021/06/16,"​In its 239th meeting, the Copom unanimously d...",A) Update of economic outlook and Copom’s base...,2021/07/01,4.25,239.0,0.75,increase
2021/08/04,"​In its 240th meeting, the Copom unanimously d...",A) Update of economic outlook and Copom’s base...,2021/08/11,5.25,240.0,1.00,increase
2021/09/22,"​In its 241st meeting, the Copom unanimously d...",A) Update of economic outlook and Copom’s base...,2021/09/28,6.25,241.0,1.00,increase
2021/10/27,"In its 242nd meeting, the Copom unanimously de...",A) Update of economic outlook and Copom’s base...,2021/11/03,7.75,242.0,1.50,increase
2021/12/08,"In its 243rd meeting, the Copom unanimously de...",A) Update of economic outlook and Copom’s base...,2021/12/14,9.25,243.0,1.50,increase
2022/02/02,"​In its 244th meeting, the Copom unanimously d...",A) Update of economic outlook and Copom’s refe...,2022/02/08,10.75,244.0,1.50,increase
2022/03/16,"​In its 245th meeting, the Copom unanimously d...",A) Update of economic outlook and Copom’s scen...,2022/05/16,11.75,245.0,1.00,increase
2022/05/04,"​In its 246th meeting, the Copom unanimously d...",A) Update of economic outlook and Copom’s scen...,2022/05/10,12.75,246.0,1.00,increase
2022/06/15,"In its 247th meeting, the Copom unanimously de...",A) Update of economic outlook and Copom’s scen...,2022/06/21,13.25,247.0,0.50,increase
2022/08/03,"In its 248th meeting, the Copom unanimously de...",A) Update of economic outlook and Copom’s scen...,2022/08/09,13.75,248.0,0.50,increase
2022/09/21,"In its 249th meeting, the Copom decided to mai...",A) Update of economic outlook and Copom’s scen...,2022/09/27,13.75,249.0,0.00,mantain
2022/10/26,"In its 250th meeting, the Copom decided to mai...",A) Update of economic outlook and Copom’s scen...,2022/11/01,13.75,250.0,0.00,mantain
2022/12/07,"In its 251st meeting, Copom decided to maintai...",A) Update of economic outlook and Copom’s scen...,2022/12/13,13.75,251.0,0.00,mantain
2023/02/01,"In its 252nd meeting, Copom decided to maintai...",A) Update of economic outlook and Copom’s scen...,2023/02/07,13.75,252.0,0.00,mantain
2023/03/22,Since its previous meeting of the Monetary Pol...,A) Update of economic outlook and Copom’s scen...,2023/03/28,13.75,253.0,0.00,mantain
2023/05/03,The global environment remains challenging. Th...,A) Update of economic outlook and Copom’s scen...,2023/05/09,13.75,254.0,0.00,mantain